format = """
[╭─](#a3aed2)\
[  ](bg:#1d2230 fg:#769ff0)\
[](bg:#1d2230 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#1d2230)\
$git_branch\
$git_status\
[](fg:#394260 bg:#1d2230)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1d2230)\
$fill\
[](fg:#1d2230)\
[$character](bg:#1d2230)\
[](fg:#394260 bg:#1d2230)\
$time\n\
╰─ 
"""

[fill]
symbol = " "

[directory]
style = "fg:#e3e5e5 bg:#1d2230"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"~" = "󰋜 ~"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#4bb543 bg:#1d2230)]($style)'

[git_status]
format = "[[$untracked](fg:#89dceb bg:#1d2230)[$modified](fg:#f9e2af bg:#1d2230)[$staged](fg:#f9e2af bg:#1d2230)[$deleted](fg:#f38ba8 bg:#1d2230)($ahead_behind$stashed)](fg:#a6e3a1 bg:#1d2230)"
untracked = "$count? "
modified = "$count! "
deleted = "$count- "
staged = "$count+ "
stashed = "$count* "

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#D34516 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[   $time  ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
success_symbol = '[✔](fg:#4bb543 bg:#1d2230)'
error_symbol = '[✗](fg:#ff2c2c bg:#1d2230)'
