# exec-once=waybar
exec-once=noctalia-shell
exec-once=swaybg -i ~/.wallpapers/wallpaper.png
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots

xkb_rules_layout=fr

new_is_master=0
enable_hotarea=0

source=./monitors.conf
source=./decoration.conf
source=./windows.conf
source=./bindings.conf
source=./scroller.conf
